### ISSUE TITLE
Usability issue

### ISSUE THREAD

**Issue by ERO001** [maysl/fische#2]
For those nontechnicals interested in Fische, what do we do after "Please pipe me some data!" to get Fische to work?

Thank you.

**Comment by maysl** [comment]
I am neither good at designing user interfaces nor have I ever claimed I am. Maybe someone wants to volunteer for this part, or at least for the user documentation?

Fische tries to tell you what it wants: Audio data through a pipe.

``` bash
data_producing_program | fische
```

For a "data producing program" check out sox, it's great! (plus there's an example on 26elf.at)

**Comment by maysl** [comment]
Hm, seems the question has been deleted. This was it:

## I have fische 4 producing very fast visualisation — there is a sox problem ?

## Even on -d4 it's very fast.

Difficult question. (But no, it's probably not related to sox)
Does it make a difference whether you run in fullscreen or windowed mode?
Do you notice a speed difference between -d2 and -d4?

**Comment by meltylang** [comment]
Yes, I'm deleted it because i was want to recheck everything.

My system:
Debian 7, Linux 3.2.0-4-686-pae #1 SMP Debian 3.2.51-1 i686 GNU/Linux, Intel Core 2 Due E6750, 4GB RAM, NVIDIA GT640 2GB VRAM, Alsa→PulseAudio sound stack.

run command:
sox -d -c2 -b16 -traw - | ./fische -n0 -d3
sox stream offcourse configured in pulse to use right sound stream.

> Difficult question. (But no, it's probably not related to sox)
> Does it make a difference whether you run in fullscreen or windowed mode?
> No.
> Do you notice a speed difference between -d2 and -d4?

I only can use values start from -d0 to -d3. -d4 results in «fische failed to start: height value out of range (16 <= height <= 2048)».
-d0-1-2 shows no huge difference, just slight changes, related, i think, to virtual resolution change (or something like that). -d3 is slower, but again just because of resolution changes.
But there is another thing — even without any sound fische shows some kind of «fluctuations».

And I missing (p)ause feature.

**Comment by maysl** [comment]
Sorry, my mistake. There's no -d4, of course.

From your description I take it you are familiar with fische3. When you
say the fische4 animation is very fast, do you mean faster than fische3?
This is - to some extent - normal. The target fps has increased from 30
to 50 iirc.

I will add the pause feature. Should be no problem.

**Comment by meltylang** [comment]
> From your description I take it you are familiar with fische3.
> Yes, I am!

This not just faster, it's really often changes from «circles» to «lines», and transitions are fast and often too.

**Comment by meltylang** [comment]
Now anything is fine. And thank you for great work!
